# ====================================================================================================
# YOLO + ByteTrack + Traffic Counting Configuration
# ====================================================================================================

# ----------------------------------------------------------------------------------------------------
# Input / Output
# ----------------------------------------------------------------------------------------------------

video_path: datasets/videos/traffic.mp4
output_path: runs/pipeline/traffic_counting.mp4


# ----------------------------------------------------------------------------------------------------
# YOLO
# ----------------------------------------------------------------------------------------------------

model_path: yolo11n.pt
device: 0
conf: 0.15
imgsz: 1280


# ----------------------------------------------------------------------------------------------------
# ByteTrack
# ----------------------------------------------------------------------------------------------------

max_history: 30


# ----------------------------------------------------------------------------------------------------
# Counting Lines
# ----------------------------------------------------------------------------------------------------

line_a:
  - [320, 550]
  - [570, 550]

line_b:
  - [590, 550]
  - [840, 550]

line_tolerance: 5